[package]
name = "karo-connection"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
bytes = "1.1"
log = "0.4"
tokio = { version = "1.19", features = [
    "sync",
    "io-util",
    "net",
    "time",
    "macros",
] }
