[package]
name = "karo-common-rpc"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
bson = "2.3"
log = "0.4"
serde = "1.0"
tokio = { version = "1.19", features = ["sync", "io-util", "net"] }

karo-common-connection = { path = "../karo-common-connection" }
